//boxjs粘贴会话至{}
module.exports ={
	"id": "rl",
	"name": "燃旅视频",
	"keys": ["rlurl", "rlurl2", "rlurl3", "rlurl4", "rlurl5", "rlurl6", "rlurl7", "rlurl8", "rlurl9", "rlurl10", "rlurl11", "rlurl12", "rlurl13", "rlurl14", "rlurl15", "rlurl16", "rlurl17", "rlurl18", "rlurl19", "rlurl20"],
	"author": "@ziye",
	"settings": [{
		"id": "rlSuffix",
		"name": "当前账号",
		"val": "1",
		"type": "number",
		"desc": "当前抓取ck记录的账号序号，如：1、2、3、"
	}, {
		"id": "rlCount",
		"name": "账号个数",
		"val": "1",
		"type": "number",
		"desc": "指定任务最多跑几个账号，根据抓取的账号数据个数来设值"
	}, {
		"id": "rlXH",
		"name": "循环获取CK",
		"val": "0",
		"type": "number",
		"desc": "0关闭 1开启,默认关闭"
	}, {
		"id": "rlXYZ",
		"name": "执行概率",
		"val": "100",
		"type": "number",
		"desc": "0不执行 可设置0-100,默认百分百"
	}, {
		"id": "rlnotifyttt",
		"name": "推送控制",
		"val": "1",
		"type": "number",
		"desc": "0关闭，1推送,默认12点以及23点推送"
	}, {
		"id": "rlnotifyInterval",
		"name": "通知控制",
		"val": "2",
		"type": "number",
		"desc": "0关闭，1为 所有通知，2为 12，23 点通知，3为 6，12，18，23 点通知 "
	}, {
		"id": "rlMinutes",
		"name": "推送-通知 分钟控制",
		"val": "10",
		"type": "number",
		"desc": "推送以及通知控制在什么分钟段，可设置0-59,默认0到10"
	}],
	"repo": "https://cdn.jsdelivr.net/gh/ziye888/JavaScript@main/Task/rl.js",
	"icons": ["https://cdn.jsdelivr.net/gh/ziye888/JavaScript@main/Task/rl.png", "https://cdn.jsdelivr.net/gh/ziye888/JavaScript@main/Task/rl.png"],
	"script": "https://cdn.jsdelivr.net/gh/ziye888/JavaScript@main/Task/rl.js",
	"icon": "https://cdn.jsdelivr.net/gh/ziye888/JavaScript@main/Task/rl.png",
	"favIcon": "mdi-star-outline",
	"favIconColor": "grey",
	"datas": [{
		"key": "rlurl",
		"val": "access_token=f2e1d57418bb3d6a0439b494f3468a75&client=1&member_id=1263279&redouble=1&user_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJSYW5sdiBKV1QiLCJpYXQiOjE2MjE0Mjc2MTUsImV4cCI6MzI0Mjg1NTIzMCwiYXVkIjoiUmFubHYiLCJzdWIiOiJSYW5sdiIsImRhdGEiOnsibWVtYmVyX2lkIjoxMjYzMjc5LCJhdmF0YXIiOiJodHRwOlwvXC9yYW5sdi5sdmZhY24uY29tXC9zdGF0aWNcL21vZHVsZVwvYWRtaW5cL2ltZ1wvZGVmYXVsdF9oZWFkLmpwZyIsIm5pY2tuYW1lIjoiXHU3NTI4XHU2MjM3ODA5MjM1NjQiLCJtb2JpbGUiOiIxMzkxNTM4MDUyOCJ9fQ.SnvOlhuvGrm5Af7u0nYg3vCqbgRRouyjvRMCkgz6SGs&uuid=C2D333CD-970F-4231-9643-6331CCD7F85B&video_id=61453"
	}, {
		"key": "rlurl2",
		"val": ""
	}, {
		"key": "rlurl3",
		"val": ""
	}, {
		"key": "rlurl4",
		"val": ""
	}, {
		"key": "rlurl5",
		"val": ""
	}, {
		"key": "rlurl6",
		"val": ""
	}, {
		"key": "rlurl7",
		"val": ""
	}, {
		"key": "rlurl8",
		"val": ""
	}, {
		"key": "rlurl9",
		"val": ""
	}, {
		"key": "rlurl10",
		"val": ""
	}, {
		"key": "rlurl11",
		"val": ""
	}, {
		"key": "rlurl12",
		"val": ""
	}, {
		"key": "rlurl13",
		"val": ""
	}, {
		"key": "rlurl14",
		"val": ""
	}, {
		"key": "rlurl15",
		"val": ""
	}, {
		"key": "rlurl16",
		"val": ""
	}, {
		"key": "rlurl17",
		"val": ""
	}, {
		"key": "rlurl18",
		"val": ""
	}, {
		"key": "rlurl19",
		"val": ""
	}, {
		"key": "rlurl20",
		"val": ""
	}],
	"sessions": [],
	"isLoaded": true
}